### ISSUE TITLE
Pseudo-class cannot run on wxc-button

### ISSUE THREAD

**Issue by ding-hai** [alibaba/weex-ui#290]
weex :   v1.3.8
 - weexpack : v1.2.3
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

    "weex-ui": "^0.6.4",

when I use ':activite ' on the compontent wxc-button.I cannot work on the web platform,and sometime I can not run on android platform.
My code 
```html

    <text class="text">1</text>
    <text class="text">2</text>
    <text class="text">3</text>
    <text class="text">4</text>

    <wxc-button class='btn' text="我是按钮" type='blue' size='small' @wxcButtonClicked="onClick('blue')"></wxc-button>
    <wxc-button class='btn' text="我是按钮" type='yellow' size='medium' @wxcButtonClicked="onClick('yellow')"></wxc-button>
    <wxc-button class='btn' text="我是按钮" type='red' size='big' @wxcButtonClicked="onClick('red')"></wxc-button>
    <wxc-button class='btn' text="我是按钮" type='white' size='full' @wxcButtonClicked="onClick('white')"></wxc-button>
    <wxc-button class='btn' text="我是自定义style的按钮" :disable='true' :btn-style="{ backgroundColor: '#00dd00',width:'750px'}" @wxcButtonClicked="onClick('green')"></wxc-button>
```
```css

.btn {
    margin-top: 60px;
}

.btn:active{
    color: #aabbff !important;
    background-color: green;

}

.text {
    width:300px;
    height:100px;
    margin-top: 40px;
    margin-bottom: 40px;
    background-color: yellow;
    color: black;
    font-size: 36px;
}
.text:active{
    color: #f0f0f2;
    background-color: black;
}
```

the  ':activite' can work on compontent 'text',but it cannot run on wxc-compontent.
